server:
  port: 9012
spring:
  application:
     name: springboot-redis
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: REDIS

  datasource:
    url: jdbc:mysql://localhost:3306/springboot_redis
    username: root
    password: kishor@2233#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate-dialect: org.hibernate.dialect.MYSQL8Dialect